updated dependencies
theturnout/court-data-pipeline pull request #14
Opened 2023-12-20 23:10 UTC by bguayante

2023-12-20 23:16 UTC, jungshadow requested changes
If the results directory is generated from running the program, should it be checked into the repo?

2023-12-20 23:16 UTC, jungshadow commented on queries/results/.dir
@bguayante Why the empty file?

2023-12-20 23:31 UTC, bguayante commented
> If the results directory is generated from running the program, should it be checked into the repo?

It throws a "file not found" error if the folder doesn't already exist. The folder must have been ignored during initial development so it slipped through, though I recall cloning and testing on a fresh install.

Perhaps a better way to approach it would be to add a line to check for the folder in the query script and create it if it doesn't exist.

2023-12-21 02:11 UTC, jungshadow commented
Either that or you should have it in the instructions to create the folder. I'd generally leave it up to the app to create its own output folder and/or have it configurable.

2023-12-21 22:12 UTC, bguayante commented
@jungshadow I added support for the user to specify the export location as an argument when running the script. If no argument is provided, it will default to `queries/results/`. In both cases, the directory will be created if it does not already exist.

2023-12-26 18:44 UTC, jungshadow approved these changes
Fine by me. Just one comment for future development.

2023-12-26 18:44 UTC, jungshadow commented on queries/run_query.py
> +            "--loc",
`--output`, `--output-dir`, or `-o` tends to be the default for command line programs for output locations, but this is an improvement on the previous functionality and not a deal breaker for me.

2024-01-11 19:42 UTC, merged